ones_project_url: "https://api.ones.ai/project/v1"
log_path: "./reminder.log"
debug: false
account: "wuxingjuan@ones.ai"
password: "juan1997"
team_uuid: "RDjYMhKq"
task_crontab: "0 15/15 18 ? * MON-FRI"
robot_list:
  - robot_name: "工时机器人"
    robot_key: "d779637b-21ef-4a86-9a5d-7d43d83a55cc"
    department_uuid: "XGMhZJ3x"
    user_mappings:
      - ones_userid: "tG4oG1mD"
        wechat_userid: "ChuYang"
      - ones_userid: "AbnBqcew"
        wechat_userid: "WuXingJuan"
      - ones_userid: "Hcjbve3m"
        wechat_userid: "杨洋"
      - ones_userid: "5YTbVihe"
        wechat_userid: "PengQuanXin"
      - ones_userid: "WpENBotT"
        wechat_userid: "gx_xy"