ones_project_url: "https://api.ones.ai/project/v1"
log_path: "./reminder.log"
debug: true
account: "wuxingjuan@ones.ai"
password: "juan1997"
team_uuid: "RDjYMhKq"
task_crontab: "0/5 * * * * MON-FRI"
robot_list:
  - robot_name: "工时机器人"
    robot_key: "d61a6d1d-64b8-49ef-a89e-a705829fc311"
    department_uuid: "XGMhZJ3x"
    user_mappings:
      - ones_userid: "tG4oG1mD"
        wechat_userid: "ChuYang"
      - ones_userid: "AbnBqcew"
        wechat_userid: "WuXingJuan"
      - ones_userid: "Hcjbve3m"
        wechat_userid: "杨洋"
      - ones_userid: "5YTbVihe"
        wechat_userid: "PengQuanXin"
      - ones_userid: "WpENBotT"
        wechat_userid: "gx_xy"