ones_project_url: "https://api.ones.ai/project/v1"
user: "user1"
password: "password1"
team_uuid: "RDjYMhKq"
msg_content: "请以下人员记得登记工时。\n"
task_crontab: "0 15/15 18 ? * MON-FRI"
#task_crontab: "0/1 * 18 ? * MON-FRI"
bot_list:
  - bot_name: "工时机器人"
    bot_key: "d779637b-21ef-4a86-9a5d-7d43d83a55cc"
    department_uuid: "XGMhZJ3x"
    user_mappings:
      - ones_userid: "tG4oG1mD"
        wechat_userid: "ChuYang"
      - ones_userid: "AbnBqcew"
        wechat_userid: "WuXingJuan"
      - ones_userid: "Hcjbve3m"
        wechat_userid: "杨洋"
      - ones_userid: "5YTbVihe"
        wechat_userid: "PengQuanXin"
      - ones_userid: "WpENBotT"
        wechat_userid: "gx_xy"